site_name: Daniel Mermelstein
site_url: http://danielmermelstein.com

nav:
  - Home: index.md
  - Projects:
    - Overview: projects.md
    - Downwinder Forecast: projects/downwinder.md
    - NYC 3K Finder: projects/nyc3k.md
    - Snowquery: projects/snowquery.md
    - Simple dbt Runner: projects/simple-dbt-runner.md
    - Haggadah Translation: projects/haggadah_translation.md

theme:
  name: mkdocs # A very basic theme. Others: readthedocs, material, bootstrap
  # To achieve a 90's/early 2000's look, you can add custom CSS:
  extra_css:
    - css/custom.css 
  # (You would create docs/css/custom.css for this)

# Optional: Add plugins here if needed
# plugins:
#   - search
